version: '3.8'

services:
  app:
    image: order-api
    build: .
    container_name: order-api
    ports:
      - "8080:8080"
    depends_on:
      - rabbitmq
      - db
  db:
    platform: linux/x86_64
    image: mysql:5.7
    container_name: mysql-db
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: mysqldb
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    ports:
      - "3306:3306"

  rabbitmq:
    image: "rabbitmq:3-management"
    container_name: 'rabbitmq'
    restart: always
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin
    ports:
      - "15672:15672"
      - "5672:5672"